/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import dados.AppDao;
import static java.awt.image.ImageObserver.HEIGHT;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author lucas.pcaldara
 */
public class CadastroDeTimes extends javax.swing.JFrame {

    /**
     * Creates new form GestaoConteudo
     */
    public CadastroDeTimes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtEquipe = new javax.swing.JTextField();
        txtQTD = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        cmbCursos = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Times");
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Quantidade de Membros");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 160, 160, 30);
        getContentPane().add(txtID);
        txtID.setBounds(220, 60, 190, 30);
        getContentPane().add(txtEquipe);
        txtEquipe.setBounds(220, 110, 190, 30);
        getContentPane().add(txtQTD);
        txtQTD.setBounds(220, 160, 190, 30);

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cadastrar ID da Equipe");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 60, 140, 30);

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nome da Equipe");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 110, 130, 30);

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Curso");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(100, 230, 130, 30);

        btnCadastrar.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar);
        btnCadastrar.setBounds(240, 303, 100, 30);

        cmbCursos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gestão de Equipes", "Programação front-end", "Análise e Gerenciamento de Riscos", "Oracle SQL" }));
        cmbCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCursosActionPerformed(evt);
            }
        });
        getContentPane().add(cmbCursos);
        cmbCursos.setBounds(220, 230, 190, 30);

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 600, 420);

        setSize(new java.awt.Dimension(616, 428));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCursosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCursosActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        String nome, curso, i, q;
        
        nome = txtEquipe.getText();
        curso = cmbCursos.getSelectedItem().toString();
        i = txtID.getText();
        q = txtQTD.getText();
        int id = Integer.parseInt(i);
        int qtd = Integer.parseInt(q);
        
        try{
            new AppDao().cadastroTimes(id, nome, curso, qtd);
            
            JOptionPane.showMessageDialog(null, "Equipe cadastrada com sucesso");
            
            txtEquipe.setText("");
            cmbCursos.requestFocus();
            txtID.setText("");
            txtQTD.setText("");
            
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao tentar localizar o Driver JDBC", nome, HEIGHT);
        } catch (SQLException ex) {
            if (ex.getMessage().contains("Duplicate entry")) {
                JOptionPane.showMessageDialog(null, "Equipe já cadastrada", nome, HEIGHT);
            } else {
                JOptionPane.showMessageDialog(null, "Erro na conexão" + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroDeTimes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroDeTimes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroDeTimes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroDeTimes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroDeTimes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JComboBox<String> cmbCursos;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtEquipe;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtQTD;
    // End of variables declaration//GEN-END:variables
}
