/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import telas.Cursos.CursoAGR;
import telas.Cursos.CursoSQL;
import telas.Cursos.CursoProgFrontEnd;
import telas.Cursos.CursoGE;

/**
 *
 * @author lucas.pcaldara
 */
public class ListaDeCursos extends javax.swing.JFrame {

    /**
     * Creates new form ListaDeCursos
     */
    public ListaDeCursos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbCursos = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnVeri = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lista de Cursos");
        getContentPane().setLayout(null);

        cmbCursos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gestão de Equipes", "Programação front-end", "Análise e Gerenciamento de Riscos", "Oracle SQL" }));
        getContentPane().add(cmbCursos);
        cmbCursos.setBounds(170, 80, 170, 40);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Visualizar cursos:");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 86, 120, 30);

        btnVeri.setBackground(new java.awt.Color(0, 0, 102));
        btnVeri.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        btnVeri.setForeground(new java.awt.Color(255, 255, 255));
        btnVeri.setText("Verificar");
        btnVeri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVeriActionPerformed(evt);
            }
        });
        getContentPane().add(btnVeri);
        btnVeri.setBounds(200, 170, 100, 30);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 540, 330);

        setSize(new java.awt.Dimension(551, 337));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVeriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVeriActionPerformed
        String c;
        c = cmbCursos.getSelectedItem().toString();
        
        if(c.equals("Gestão de Equipes")){
            new CursoGE().setVisible(true);
        } else if (c.equals("Programação front-end")){
            new CursoProgFrontEnd().setVisible(true);
        } else if(c.equals("Análise e Gerenciamento de Riscos")){
            new CursoAGR().setVisible(true);
        } else{
         new CursoSQL().setVisible(true);
        }
    }//GEN-LAST:event_btnVeriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaDeCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaDeCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaDeCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaDeCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaDeCursos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVeri;
    private javax.swing.JComboBox<String> cmbCursos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
